const OperatorType = @import("OperatorType.zig").OperatorType;
const TensorType = @import("TensorType.zig").TensorType;
pub const model = .{
    .tensors = .{
        .{
            .name = "Parameter193",
            .type = f32,
            .shape = .{ 16, 4, 4, 10 },
            .tensor = TensorType.Fixed,
            .params = .{ .data = @import("weights/Parameter193.zig") },
        },
        .{
            .name = "Parameter87",
            .type = f32,
            .shape = .{ 16, 8, 5, 5 },
            .tensor = TensorType.Fixed,
            .params = .{ .data = @import("weights/Parameter87.zig") },
        },
        .{
            .name = "Parameter5",
            .type = f32,
            .shape = .{ 8, 1, 5, 5 },
            .tensor = TensorType.Fixed,
            .params = .{ .data = @import("weights/Parameter5.zig") },
        },
        .{
            .name = "Parameter6",
            .type = f32,
            .shape = .{ 8, 1, 1 },
            .tensor = TensorType.Fixed,
            .params = .{ .data = @import("weights/Parameter6.zig") },
        },
        .{
            .name = "Parameter88",
            .type = f32,
            .shape = .{ 16, 1, 1 },
            .tensor = TensorType.Fixed,
            .params = .{ .data = @import("weights/Parameter88.zig") },
        },
        .{
            .name = "Pooling160_Output_0_reshape0_shape",
            .type = i64,
            .shape = .{2},
            .tensor = TensorType.Fixed,
            .params = .{ .data = @import("weights/Pooling160_Output_0_reshape0_shape.zig") },
        },
        .{
            .name = "Parameter193_reshape1_shape",
            .type = i64,
            .shape = .{2},
            .tensor = TensorType.Fixed,
            .params = .{ .data = @import("weights/Parameter193_reshape1_shape.zig") },
        },
        .{
            .name = "Parameter194",
            .type = f32,
            .shape = .{ 1, 10 },
            .tensor = TensorType.Fixed,
            .params = .{ .data = @import("weights/Parameter194.zig") },
        },
        .{
            .name = "Input3",
            .type = f32,
            .shape = .{ 1, 1, 28, 28 },
            .tensor = TensorType.Input,
            .params = {},
        },
        .{
            .name = "Plus214_Output_0",
            .type = f32,
            .shape = .{ 1, 10 },
            .tensor = TensorType.Output,
            .params = {},
        },
        .{
            .name = "Parameter193_reshape1",
            .type = f32,
            .shape = .{ 256, 10 },
            .tensor = TensorType.Computed,
            .params = {},
        },
        .{
            .name = "Convolution28_Output_0",
            .type = f32,
            .shape = .{ 1, 8, 28, 28 },
            .tensor = TensorType.Computed,
            .params = {},
        },
        .{
            .name = "Plus30_Output_0",
            .type = f32,
            .shape = .{ 1, 8, 28, 28 },
            .tensor = TensorType.Computed,
            .params = {},
        },
        .{
            .name = "ReLU32_Output_0",
            .type = f32,
            .shape = .{ 1, 8, 28, 28 },
            .tensor = TensorType.Computed,
            .params = {},
        },
        .{
            .name = "Pooling66_Output_0",
            .type = f32,
            .shape = .{ 1, 8, 14, 14 },
            .tensor = TensorType.Computed,
            .params = {},
        },
        .{
            .name = "Convolution110_Output_0",
            .type = f32,
            .shape = .{ 1, 16, 14, 14 },
            .tensor = TensorType.Computed,
            .params = {},
        },
        .{
            .name = "Plus112_Output_0",
            .type = f32,
            .shape = .{ 1, 16, 14, 14 },
            .tensor = TensorType.Computed,
            .params = {},
        },
        .{
            .name = "ReLU114_Output_0",
            .type = f32,
            .shape = .{ 1, 16, 14, 14 },
            .tensor = TensorType.Computed,
            .params = {},
        },
        .{
            .name = "Pooling160_Output_0",
            .type = f32,
            .shape = .{ 1, 16, 4, 4 },
            .tensor = TensorType.Computed,
            .params = {},
        },
        .{
            .name = "Pooling160_Output_0_reshape0",
            .type = f32,
            .shape = .{ 1, 256 },
            .tensor = TensorType.Computed,
            .params = {},
        },
        .{
            .name = "Times212_Output_0",
            .type = f32,
            .shape = .{ 1, 10 },
            .tensor = TensorType.Computed,
            .params = {},
        },
    },
    .operators = .{
        .{
            .name = "Times212_reshape1",
            .op = OperatorType.Reshape,
            .type = f32,
            .params = .{
                .inp_0 = "Parameter193",
                .inp_0_shape = .{ 16, 4, 4, 10 },
                .inp_0_type = "f32",
                .inp_1 = "Parameter193_reshape1_shape",
                .inp_1_shape = .{2},
                .inp_1_type = "i64",
                .out_0 = "Parameter193_reshape1",
                .out_0_shape = .{ 256, 10 },
                .out_0_type = "f32",
            },
        },
        .{
            .name = "Convolution28",
            .op = OperatorType.Conv,
            .type = f32,
            .params = .{
                .kernel_shape = .{ 5, 5 },
                .strides = .{ 1, 1 },
                .auto_pad = "SAME_UPPER",
                .group = 1,
                .dilations = .{ 1, 1 },
                .inp_0 = "Input3",
                .inp_0_shape = .{ 1, 1, 28, 28 },
                .inp_0_type = "f32",
                .inp_1 = "Parameter5",
                .inp_1_shape = .{ 8, 1, 5, 5 },
                .inp_1_type = "f32",
                .out_0 = "Convolution28_Output_0",
                .out_0_shape = .{ 1, 8, 28, 28 },
                .out_0_type = "f32",
            },
        },
        .{
            .name = "Plus30",
            .op = OperatorType.Add,
            .type = f32,
            .params = .{
                .inp_0 = "Convolution28_Output_0",
                .inp_0_shape = .{ 1, 8, 28, 28 },
                .inp_0_type = "f32",
                .inp_1 = "Parameter6",
                .inp_1_shape = .{ 8, 1, 1 },
                .inp_1_type = "f32",
                .out_0 = "Plus30_Output_0",
                .out_0_shape = .{ 1, 8, 28, 28 },
                .out_0_type = "f32",
            },
        },
        .{
            .name = "ReLU32",
            .op = OperatorType.Relu,
            .type = f32,
            .params = .{
                .inp_0 = "Plus30_Output_0",
                .inp_0_shape = .{ 1, 8, 28, 28 },
                .inp_0_type = "f32",
                .out_0 = "ReLU32_Output_0",
                .out_0_shape = .{ 1, 8, 28, 28 },
                .out_0_type = "f32",
            },
        },
        .{
            .name = "Pooling66",
            .op = OperatorType.MaxPool,
            .type = f32,
            .params = .{
                .kernel_shape = .{ 2, 2 },
                .strides = .{ 2, 2 },
                .pads = .{ 0, 0, 0, 0 },
                .auto_pad = "NOTSET",
                .inp_0 = "ReLU32_Output_0",
                .inp_0_shape = .{ 1, 8, 28, 28 },
                .inp_0_type = "f32",
                .out_0 = "Pooling66_Output_0",
                .out_0_shape = .{ 1, 8, 14, 14 },
                .out_0_type = "f32",
            },
        },
        .{
            .name = "Convolution110",
            .op = OperatorType.Conv,
            .type = f32,
            .params = .{
                .kernel_shape = .{ 5, 5 },
                .strides = .{ 1, 1 },
                .auto_pad = "SAME_UPPER",
                .group = 1,
                .dilations = .{ 1, 1 },
                .inp_0 = "Pooling66_Output_0",
                .inp_0_shape = .{ 1, 8, 14, 14 },
                .inp_0_type = "f32",
                .inp_1 = "Parameter87",
                .inp_1_shape = .{ 16, 8, 5, 5 },
                .inp_1_type = "f32",
                .out_0 = "Convolution110_Output_0",
                .out_0_shape = .{ 1, 16, 14, 14 },
                .out_0_type = "f32",
            },
        },
        .{
            .name = "Plus112",
            .op = OperatorType.Add,
            .type = f32,
            .params = .{
                .inp_0 = "Convolution110_Output_0",
                .inp_0_shape = .{ 1, 16, 14, 14 },
                .inp_0_type = "f32",
                .inp_1 = "Parameter88",
                .inp_1_shape = .{ 16, 1, 1 },
                .inp_1_type = "f32",
                .out_0 = "Plus112_Output_0",
                .out_0_shape = .{ 1, 16, 14, 14 },
                .out_0_type = "f32",
            },
        },
        .{
            .name = "ReLU114",
            .op = OperatorType.Relu,
            .type = f32,
            .params = .{
                .inp_0 = "Plus112_Output_0",
                .inp_0_shape = .{ 1, 16, 14, 14 },
                .inp_0_type = "f32",
                .out_0 = "ReLU114_Output_0",
                .out_0_shape = .{ 1, 16, 14, 14 },
                .out_0_type = "f32",
            },
        },
        .{
            .name = "Pooling160",
            .op = OperatorType.MaxPool,
            .type = f32,
            .params = .{
                .kernel_shape = .{ 3, 3 },
                .strides = .{ 3, 3 },
                .pads = .{ 0, 0, 0, 0 },
                .auto_pad = "NOTSET",
                .inp_0 = "ReLU114_Output_0",
                .inp_0_shape = .{ 1, 16, 14, 14 },
                .inp_0_type = "f32",
                .out_0 = "Pooling160_Output_0",
                .out_0_shape = .{ 1, 16, 4, 4 },
                .out_0_type = "f32",
            },
        },
        .{
            .name = "Times212_reshape0",
            .op = OperatorType.Reshape,
            .type = f32,
            .params = .{
                .inp_0 = "Pooling160_Output_0",
                .inp_0_shape = .{ 1, 16, 4, 4 },
                .inp_0_type = "f32",
                .inp_1 = "Pooling160_Output_0_reshape0_shape",
                .inp_1_shape = .{2},
                .inp_1_type = "i64",
                .out_0 = "Pooling160_Output_0_reshape0",
                .out_0_shape = .{ 1, 256 },
                .out_0_type = "f32",
            },
        },
        .{
            .name = "Times212",
            .op = OperatorType.MatMul,
            .type = f32,
            .params = .{
                .inp_0 = "Pooling160_Output_0_reshape0",
                .inp_0_shape = .{ 1, 256 },
                .inp_0_type = "f32",
                .inp_1 = "Parameter193_reshape1",
                .inp_1_shape = .{ 256, 10 },
                .inp_1_type = "f32",
                .out_0 = "Times212_Output_0",
                .out_0_shape = .{ 1, 10 },
                .out_0_type = "f32",
            },
        },
        .{
            .name = "Plus214",
            .op = OperatorType.Add,
            .type = f32,
            .params = .{
                .inp_0 = "Times212_Output_0",
                .inp_0_shape = .{ 1, 10 },
                .inp_0_type = "f32",
                .inp_1 = "Parameter194",
                .inp_1_shape = .{ 1, 10 },
                .inp_1_type = "f32",
                .out_0 = "Plus214_Output_0",
                .out_0_shape = .{ 1, 10 },
                .out_0_type = "f32",
            },
        },
    },
};
